// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBirF1uxwSmG1Pwp3wrB-cyWeI0_H35AKc',
    appId: '1:734693085909:web:b18ac0237718b7ebf8885c',
    messagingSenderId: '734693085909',
    projectId: 'chat-app-f96db',
    authDomain: 'chat-app-f96db.firebaseapp.com',
    storageBucket: 'chat-app-f96db.appspot.com',
    measurementId: 'G-5889EH8VDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiKkPchZy0iREwVL96F4RrZMNfRmNHtg8',
    appId: '1:734693085909:android:f1f57281f85a8fc4f8885c',
    messagingSenderId: '734693085909',
    projectId: 'chat-app-f96db',
    storageBucket: 'chat-app-f96db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiabgucWI1nKprluJmXRAuShip15QShJc',
    appId: '1:734693085909:ios:b7ba1bb3d64b5cf2f8885c',
    messagingSenderId: '734693085909',
    projectId: 'chat-app-f96db',
    storageBucket: 'chat-app-f96db.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiabgucWI1nKprluJmXRAuShip15QShJc',
    appId: '1:734693085909:ios:d241140f66feacd6f8885c',
    messagingSenderId: '734693085909',
    projectId: 'chat-app-f96db',
    storageBucket: 'chat-app-f96db.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
